################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Developed By [DataFortress.cloud](https://www.datafortress.cloud/)"



################################### French language #####################################
[de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 2
home = "Home"
# copyright
copyright = "Developed By [DataFortress.cloud](https://www.datafortress.cloud/)"